const altTexts = [
  "Fresh sod installation. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Stone walkway design. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Mulched garden bed. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Trimmed hedges. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Flower bed layout. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Backyard patio. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Decorative pavers. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Raised garden. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Outdoor fire pit. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Retaining wall. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Curb appeal upgrade. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Rock garden. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Water feature. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Pergola setup. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Landscape lighting. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Gravel driveway. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Garden hammock. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Trellis with vines. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Outdoor kitchen. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Flagstone path. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Privacy hedges. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Fence border. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Decorative boulders. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Stone benches. Professional landscaping project in the Morgantown WV/Preston County area.",
  "New turf install. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Solar-lit path. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Deck with plants. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Brick edging. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Tree planting. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Butterfly garden. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Stone steps. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Landscape cleanup. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Play area turf. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Crushed stone path. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Ornamental grasses. Professional landscaping project in the Morgantown WV/Preston County area.",
  "Privacy fencing. Professional landscaping project in the Morgantown WV/Preston County area.",
];
